<?xml version="1.0" encoding="UTF-8"?>
<!--
  SDN-MPLS-ML Tech Demonstrator
  Santiago Arellano 00328370

  Modulo que produce la aplicacion interna al sistema de Apache Karaf que maneja Opendaylight para el registro de la
  aplicacion Controller Side Application requerida para receptar eventos de PacketIn y su lectura en el sistema.

  El modelo implementado actualmente se basa en un OSGi Bundle, que define el porque de la existencia de un moduloe features
  y un modulo impl que es el formato requerido por los bundles registrados en Apache Karaf dentro de Opendaylight. Ademas
  usamos el modelo de Blueprint Containers para definir un sistema sin importar directamente OSGi sino que nos basamos
  en las librerias de org.opendaylight.odlparent bundle-parent que contiene librerias necesarias para su funcionamiento
  base.

  El modulo se organiza de la siguiente manera:
  1. groupId: com.sma.sdn que corresponde a sma (SDN-MPLS-AI root de todos los nombres de subsistemas de la topologia) ,
  sdn el componente que se esta modificando sobre su implementacion base ODL
  2. arifactId: sdn-mpls-ml-cs-app-impl que corresponde al componente de implementacion del bundle real
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">


    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.opendaylight.odlparent</groupId>
        <artifactId>bundle-parent</artifactId>
        <version>14.1.6</version>
        <relativePath/>
    </parent>

    <groupId>com.sma.sdn</groupId>
    <artifactId>sdn-mpls-ml-cs-app-impl</artifactId>
    <version>0.1.0-SNAPSHOT</version>

    <!--? Definimos que vamos a implementar un bundle de OSGi-->
    <packaging>bundle</packaging>


    <name>SDN-MPLS-ML Controller Side Application - Implementation</name>
    <description>
        Controller Side Application (o en nomenclatura ODL In-Controller Application) orientada a la recepcion de eventos
        de trafico de Openflow, para la extraccion de sus caracteristicas y su clasificacion mediante una API definida en
        Python cuyo funcionamiento ya esta validado.

        Este modulo se encarga de la recepcion de senales de Openflow, clasificacion, solicitud de un camino y el posterior
        seeding de los tuneles definidos en sea LSR1 o lSR4 dependiendo de la senal recibida de Opendaylight
    </description>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mdsal.version>15.0.4</mdsal.version>
        <openflowplugin.version>0.21.3</openflowplugin.version>
        <yangtools.version>14.0.23</yangtools.version>
        <junit.jupiter.version>5.10.3</junit.jupiter.version>
    </properties>

    <repositories>
        <repository>
            <id>opendaylight-public</id>
            <name>OpenDaylight Public Repository</name>
            <url>https://nexus.opendaylight.org/content/repositories/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>org.opendaylight.mdsal</groupId>
            <artifactId>mdsal-binding-api</artifactId>
            <version>${mdsal.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.opendaylight.openflowplugin.model</groupId>
            <artifactId>model-flow-service</artifactId>
            <version>${openflowplugin.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.opendaylight.yangtools</groupId>
            <artifactId>concepts</artifactId>
            <version>${yangtools.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>
