<?xml version="1.0" encoding="UTF-8"?>
<!--

    SDN-MPLS-ML Tech Demonstrator
    Santiago Arellano 00328370

    Archivo POM general que define los modulos internos a agregar en un paquete final JAR.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!--
      Se usa la version odlparent pero light porque no necesitamos ninguna libreria externa sino solo el POM general
      definido por ODL para la agrupacion de componentes
    -->
    <parent>
        <groupId>org.opendaylight.odlparent</groupId>
        <artifactId>odlparent-lite</artifactId>
        <version>14.1.6</version>
        <relativePath/>
    </parent>

    <groupId>com.sma.sdn</groupId>
    <artifactId>sdn-mpls-ml-cs-app</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Anadimos estas tres lineas nuevas dado que requerimos, para desarrollo local, conoer
        que librerias y que importe necesitamos manejar para escribir el listener para PacketReceived
        notifications desde el controlador.-->
        <mdsal.version>15.0.4</mdsal.version>
        <openflowplugin.version>0.21.3</openflowplugin.version>
        <yangtools.version>14.0.23</yangtools.version>
    </properties>
    <modules>
        <module>impl</module>
        <module>features</module>
    </modules>



</project>