<?xml version="1.0" encoding="UTF-8"?>
<!--
    SDN-MPLS-ML Tech Demonstrator
    Santiago Arellano 00328370

    Modulo adicional que permite la definicion de un archivo feature.xml que define las librerias requeridas dentro de
    ODL para la inicializacion del modulo y para su uso.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- Maven model version. -->
    <modelVersion>4.0.0</modelVersion>

    <!--
      usamos el artefacto de ODL single-feature-parent para producir un modulo que solo genera una feature (la descripcion
      de los requerimientos y demas) hacia Karaf
    -->
    <parent>
        <groupId>org.opendaylight.odlparent</groupId>
        <artifactId>single-feature-parent</artifactId>
        <version>14.1.6</version>
        <relativePath/>
    </parent>

    <groupId>com.sma.sdn</groupId>
    <artifactId>sdn-mpls-ml-cs-app-features</artifactId>
    <version>0.1.0-SNAPSHOT</version>


    <packaging>feature</packaging>

    <name>SDN-MPLS-ML Controller Application - Karaf Feature</name>
    <description>
        Feature de Karaf usada para la instalacion del modulo directamente en el sistema de Apache Karaf
    </description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <controller.version>12.0.5</controller.version>
        <mdsal.version>15.0.4</mdsal.version>
        <openflowplugin.version>0.21.3</openflowplugin.version>
    </properties>

    <repositories>
        <repository>
            <id>opendaylight-public</id>
            <name>OpenDaylight Public Repository</name>
            <url>https://nexus.opendaylight.org/content/repositories/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.sma.sdn</groupId>
            <artifactId>sdn-mpls-ml-cs-app-impl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.opendaylight.odlparent</groupId>
            <artifactId>odl-jackson-2</artifactId>
            <classifier>features</classifier>
            <type>xml</type>
        </dependency>
        <dependency>
            <groupId>org.opendaylight.mdsal</groupId>
            <artifactId>odl-mdsal-binding-api</artifactId>
            <version>${mdsal.version}</version>
            <classifier>features</classifier>
            <type>xml</type>
        </dependency>

        <dependency>
            <groupId>org.opendaylight.controller</groupId>
            <artifactId>odl-mdsal-broker</artifactId>
            <version>${controller.version}</version>
            <classifier>features</classifier>
            <type>xml</type>
        </dependency>

        <dependency>
            <groupId>org.opendaylight.openflowplugin</groupId>
            <artifactId>odl-openflowplugin-flow-services-rest</artifactId>
            <version>${openflowplugin.version}</version>
            <classifier>features</classifier>
            <type>xml</type>
        </dependency>

        <dependency>
            <groupId>org.opendaylight.openflowplugin</groupId>
            <artifactId>odl-openflowplugin-app-table-miss-enforcer</artifactId>
            <version>${openflowplugin.version}</version>
            <classifier>features</classifier>
            <type>xml</type>
        </dependency>
    </dependencies>

</project>